// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNCWtDBmHHfCPhX0oWWrnYNflbw0kZ-uI',
    appId: '1:514455668574:web:f15736e11a63d4fecdf1cf',
    messagingSenderId: '514455668574',
    projectId: 'chat-app-89117',
    authDomain: 'chat-app-89117.firebaseapp.com',
    storageBucket: 'chat-app-89117.firebasestorage.app',
    measurementId: 'G-ML4CX4H6V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJMEwcSBosRqgm_EmSkLx9v03fsC5ie6E',
    appId: '1:514455668574:android:b7f2c77dd09b4af1cdf1cf',
    messagingSenderId: '514455668574',
    projectId: 'chat-app-89117',
    storageBucket: 'chat-app-89117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ6atD0d42_ThguVUFwtioMBerpxxAjgU',
    appId: '1:514455668574:ios:4487df3dedd90bd0cdf1cf',
    messagingSenderId: '514455668574',
    projectId: 'chat-app-89117',
    storageBucket: 'chat-app-89117.firebasestorage.app',
    iosBundleId: 'com.example.project10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ6atD0d42_ThguVUFwtioMBerpxxAjgU',
    appId: '1:514455668574:ios:4487df3dedd90bd0cdf1cf',
    messagingSenderId: '514455668574',
    projectId: 'chat-app-89117',
    storageBucket: 'chat-app-89117.firebasestorage.app',
    iosBundleId: 'com.example.project10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNCWtDBmHHfCPhX0oWWrnYNflbw0kZ-uI',
    appId: '1:514455668574:web:a529367503cd8b2bcdf1cf',
    messagingSenderId: '514455668574',
    projectId: 'chat-app-89117',
    authDomain: 'chat-app-89117.firebaseapp.com',
    storageBucket: 'chat-app-89117.firebasestorage.app',
    measurementId: 'G-3DEMS1366L',
  );
}
